# Generated by Django 4.1 on 2024-09-11 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_curso_estudiante"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="curso",
            name="estudiante",
        ),
        migrations.RemoveField(
            model_name="curso",
            name="profesor",
        ),
        migrations.AddField(
            model_name="curso",
            name="estudiante",
            field=models.ManyToManyField(related_name="cursos", to="main.estudiante"),
        ),
        migrations.AddField(
            model_name="curso",
            name="profesor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cursos",
                to="main.profesor",
            ),
        ),
    ]
