# Generated by Django 4.1 on 2024-10-26 00:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="productos/"),
        ),
        migrations.AlterField(
            model_name="producto",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Orden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "precio_total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("completada", models.BooleanField(default=False)),
                (
                    "combos",
                    models.ManyToManyField(
                        blank=True, related_name="ordenes", to="productos.combo"
                    ),
                ),
                (
                    "productos",
                    models.ManyToManyField(
                        blank=True, related_name="ordenes", to="productos.producto"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordenes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
