# Generated by Django 4.1 on 2024-10-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0002_producto_imagen_alter_producto_descripcion_orden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combo",
            name="precio_total",
            field=models.DecimalField(decimal_places=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
