# Generated by Django 4.1 on 2024-10-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0003_alter_combo_precio_total_alter_producto_precio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combo",
            name="precio_total",
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
