# Generated by Django 4.1 on 2024-10-26 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0005_alter_combo_precio_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combo",
            name="precio_total",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
