# Generated by Django 4.1 on 2024-10-26 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0006_alter_combo_precio_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orden",
            name="combos",
        ),
        migrations.RemoveField(
            model_name="orden",
            name="productos",
        ),
        migrations.AlterField(
            model_name="orden",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
