# Generated by Django 4.1 on 2024-10-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0007_remove_orden_combos_remove_orden_productos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="combo",
            name="productos",
            field=models.ManyToManyField(to="productos.producto"),
        ),
    ]
