# Generated by Django 4.1 on 2024-10-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0008_alter_combo_productos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="combo",
            name="productos",
        ),
    ]
