# Generated by Django 4.1 on 2024-10-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0009_remove_combo_productos"),
    ]

    operations = [
        migrations.AddField(
            model_name="combo",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="combo",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="combos/"),
        ),
    ]
