# Generated by Django 4.1 on 2024-10-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0011_orden_combos_orden_productos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orden",
            name="combos",
        ),
        migrations.RemoveField(
            model_name="orden",
            name="completada",
        ),
        migrations.RemoveField(
            model_name="orden",
            name="productos",
        ),
        migrations.AddField(
            model_name="orden",
            name="detalle",
            field=models.TextField(blank=True, default=""),
        ),
    ]
