# Generated by Django 4.1 on 2024-10-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0012_remove_orden_combos_remove_orden_completada_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orden",
            name="completada",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="orden",
            name="detalle",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="orden",
            name="precio_total",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
