# Generated by Django 4.1 on 2024-10-26 13:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productos", "0013_orden_completada_alter_orden_detalle_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orden",
            name="detalle",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="orden",
            name="precio_total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
    ]
